# Generated by Django 4.0.6 on 2022-07-27 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('OF', 'Offer'), ('CA', 'Category')], default='OF', max_length=2)),
                ('parentId', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('price', models.IntegerField(null=True)),
                ('children', models.TextField(null=True)),
            ],
        ),
    ]
