# Generated by Django 4.0.6 on 2022-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didenokapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='type',
            field=models.CharField(choices=[('OF', 'Offer'), ('CA', 'Category')], max_length=2),
        ),
    ]
