# Generated by Django 4.0.6 on 2022-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didenokapiapp', '0002_alter_shopunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='type',
            field=models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=8),
        ),
    ]
