# Generated by Django 4.0.6 on 2022-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didenokapiapp', '0003_alter_shopunit_date_alter_shopunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parentId',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
